dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: Awk7TNhiJdC0SHUJwmWUmVdS8aZar0rR4lRMeVlCfU9TheA4wCjBEtPuBfOYGq9HXT9x5ILKYMhiOqYlnXXNMpK/XR3NmMr8HIsXrEulzbRX7M/zuBBR/AnwulTkC2xFq2XKlTiwpZ7h3lddzzZ7wftsM2pjzY3o/JloU1zqO8Voc88z1keRA+M7n4nzIjV9o18aX7dkxHkjGF6/zi2hlmRtafrjaIvNR4CuAdeBCpyvnfLZ3uYwXoPpIO/X+KKT4jR1cIvB+RN9L6hs/5pcyTYL0hwsg1bf0v5Q0kG1HhOLzBrD2qgXT1+pIe7NK50NenY+Lz/BWJ/om6BdQ/2r8lF/4aRSplZBDJTS1ENjZ6/3sDBshEp5QR7NODHijM3hA3CjiROZwNx/rf1tAM/a892mwwDbKbu27w6AEgw0iahrzAJaAMj6eqTDKLLy5Bt3sMzkaoe6WerxQ7bx/X0oEfLJkncoczXUzbR9AQvZFohJksV0Q3K79h5Hb0xpFVMPP/O+beKD12LOfAkIH6g/3r0oT3uOeqigeq4BQkHZxkGwtLzBx2o9ZCbRuDeaTR7FNPXG0HvJIcQmHmanVu4jmcozmvk7TNEtNNLICVhf+8SiwVnywGVW7A79bsEP/1nD8akkZgkQf/h0a2xiQJxBkDPpnPPHslCwPe89ISIDiy8=
  file: Gerbers/PIN-112_gerbers.zip
  on:
    repo: w4xzr/PIN-112
  skip_cleanup: 'true'
